server:
  port: 8092

spring:
  application:
    name: detail-process
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.136.107.102:3766/detail_process?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMultiQueries=true&nullCatalogMeansCurrent=true
      username: root
      password: Passw0rd
      initial-size: 50
      min-idle: 50
      max-active: 100
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 3600000000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      poolPingQuery: select 1
      poolPingEnabled: true
      poolPingConnectionsNotUsedFor: 3600000
  main:
    allow-bean-definition-overriding: true

#flowable 相关配置
flowable:
  database-schema-update: true
#  async-executor-activate: false


